name: Check for memory errors using address sanitizer and valgrind

on:
  - workflow_call

jobs:
  sanitizer:
    name: Check Address Sanitizer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Clone igraph
        run: |
          git submodule init
          git submodule update --recursive

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install cmake ninja-build clang

      - name: Build for address sanitizer
        run: CC=clang make asan

      - name: Test block
        run: asan/examples/block

      - name: Test weighted block
        run: asan/examples/weighted_block

      - name: Test interrupt
        run: asan/examples/interrupt

      - name: Test full graph
        run: asan/examples/dense

  valgrind:
    name: Check with valgrind
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Clone igraph
        run: |
          git submodule init
          git submodule update --recursive

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install cmake ninja-build gcc valgrind

      - name: Build for valgrind
        run: make debug

      - name: unweighted
        run: make valgrind-block

      - name: weighted
        run: make valgrind-weighted_block

      - name: interrupted
        run: make valgrind-interrupt

      - name: full graph
        run: make valgrind-dense
